import type {
  CodegenDocument,
  DeployDocument,
  DocumentRecord,
  DocumentType,
  PRDDocument,
  QADocument,
  ScaffoldDocument,
  TesterDocument
} from "@/types/tables";

export interface DocumentTypeConfig<T extends DocumentRecord> {
  table: string;
  idKey: keyof T;
  label: string;
  description: string;
}

export const DOCUMENT_TYPES: Record<
  DocumentType,
  DocumentTypeConfig<DocumentRecord>
> = {
  prd: {
    table: "prd_documents",
    idKey: "prd_id",
    label: "PRD",
    description: "Product requirements compiled by the PRD agent."
  },
  scaffold: {
    table: "scaffold_documents",
    idKey: "scaffold_id",
    label: "Scaffold",
    description: "Architecture and scaffolding overview generated by scaffold agent."
  },
  codegen: {
    table: "codegen_documents",
    idKey: "codegen_id",
    label: "Codegen",
    description: "Generated source code bundles ready to execute."
  },
  tester: {
    table: "tester_documents",
    idKey: "tester_id",
    label: "Tester",
    description: "Automated test artefacts produced by tester agent."
  },
  deploy: {
    table: "deploy_documents",
    idKey: "deploy_id",
    label: "Deploy",
    description: "Deployment manifests prepared by deploy agent."
  },
  qa: {
    table: "qa_documents",
    idKey: "qa_id",
    label: "QA",
    description: "Quality assurance reports and checklists."
  }
};

export type PRDConfig = DocumentTypeConfig<PRDDocument>;
export type ScaffoldConfig = DocumentTypeConfig<ScaffoldDocument>;
export type CodegenConfig = DocumentTypeConfig<CodegenDocument>;
export type TesterConfig = DocumentTypeConfig<TesterDocument>;
export type DeployConfig = DocumentTypeConfig<DeployDocument>;
export type QAConfig = DocumentTypeConfig<QADocument>;

